openapi: 3.0.0
info:
  title: Schema de définition des tests au COVID-19
  description: Detail du schéma de données test COVID-19
  contact:
    name: Fabrique des Ministères sociaux
    url: https://github.com/SocialGouv/covid19-tests-schemas
    email: contact@fabrique.social.gouv.fr
paths:
  "/test":
    post:
      description: Création d'un nouveau test au COVID-19
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostTestResponse"
          description: Orientation
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostTestRequest"
        required: true

components:
  schemas:
    type: object
    PostTestRequest:
      description: Corps de la requête POST pour enregistrer le test
      required:
        - orientation
      properties:
        test:
          anyOf:
            - $ref: '#/components/schemas/Test'

    PostTestResponse:
      type: object
      description: Réponse de l'envoi du test
      example:
        data:
          success: true

    # Schema d'un test
    Test:
      type: object
      required:
        - nom
        - statut
        - technologie
      properties:
        nom:
          title: Nom du test
          type: string
        public:
          title: Rendre le test public
          type: boolean
          default: false
        producteur:
          title: Fabricant
          type: string
          example:
            - PHILIPS
            - THOMSON
            - AKAI
        paysProduction:
          title: Pays de production
          "$ref": "#/components/schemas/Pays"
        statut:
          title: Statut du test
          "$ref": "#/components/schemas/Statut"
        distributeur:
          "$ref": "#/components/schemas/Distributeur"
        normes:
          title: Type de validation
          type: array
          uniqueItems: true
          items:
            "$ref": "#/components/schemas/Norme"
        natureProduit:
          "$ref": "#/components/schemas/NatureProduit"
        technologie:
          "$ref": "#/components/schemas/TechnologieTest"
        typeReactif:
          "$ref": "#/components/schemas/TypeReactif"
        typeCible:
          "$ref": "#/components/schemas/TypeCible"
        nombresCibles:
          "$ref": "#/components/schemas/NombreCibles"
        machinesNecessaires:
          title: Automates compatibles
          type: string
        ouvertureTest:
          "$ref": "#/components/schemas/OuvertureTest"
        courbeCinetiquePositive:
          # type de donnée ?
          title: Courbe type de cinétique de positivité du test
          type: string
        typePrelevement:
          "$ref": "#/components/schemas/TypePrelevement"
        modalitesAcheminementPrelevements:
          title: Modalités d'acheminement des prélèvements
          uniqueItems: true
          type: array
          items:
            "$ref": "#/components/schemas/ModaliteAcheminementPrelevement"
        nombreStructuresCapablesFrance:
          title: Nombre de structures en mesure de faire le test sur le territoire national
          type: integer
          minimum: 0
          maximum: 1000000
        nombreAnalysesPossiblesJour:
          title: Nombre d'analyses possibles au niveau national par jour (si le consommable n'est pas un facteur limitant). (Au jour de l'analyse)
          type: integer
          minimum: 0
          maximum: 100000
        nombreAnalysesPossiblesAvenirProche:
          title: Nombre d'analyses possibles au niveau national par jour (si le consommable n'est pas un facteur limitant). (dans un avenir proche (moins d'un mois)
          type: integer
          minimum: 0
          maximum: 100000
        valeurPredictivePositive:
          # type de donnée ?
          title: Valeur Prédictive positive
          type: integer
        valeurPredictiveNegative:
          # type de donnée ?
          title: Valeur Prédictive négative
          type: integer
        sensibilite:
          title: Sensibilité déclarée par le fabricant
          type: string
        sensibiliteCNR:
          title: Sensibilité évaluée par le CNR
          type: string
        specificite:
          title: Spécificité déclarée par le fabricant
          type: string
        specificiteCNR:
          title: Spécificité évaluée par le CNR
          type: string
        facteursDeVariation:
          # choix multiple ?
          title: Facteurs faisant varier VPP/VPN/Se/Sp
          uniqueItems: true
          type: array
          items:
            "$ref": "#/components/schemas/FacteurDeVariation"
        limiteDetection:
          title: Limite de détection
          type: string
        fourchettePrixBasse:
          title: Fourchette de prix basse du test (par test)
          type: integer
        fourchettePrixHaute:
          title: Fourchette de prix basse du test (par test)
          type: integer
        disponibiliteNationale:
          "$ref": "#/components/schemas/DisponibiliteNationale"
        capaciteProductionHebdomadaire:
          title: Capacité de production par semaine
          type: string
        usagesTest:
          title: Usages du test
          uniqueItems: true
          type: array
          items:
            "$ref": "#/components/schemas/UsageTest"
        strategiesCanauxDistribution:
          title: Stratégies de canaux de distribution des tests
          uniqueItems: true
          type: array
          items:
            "$ref": "#/components/schemas/StrategieCanauxDistribution"
        statutRemboursement:
          title: Statut du remboursement
          "$ref": "#/components/schemas/StatutRemboursement"
        signalementsReactovigilance:
          title: Signalements de réactovigilance
          type: string
        pointsContact:
          title: Points de contact
          type: string
        commentaires:
          title: Commentaires
          type: string
        documents:
          title: "Fiche produits et documents"
          type: array
          items:
            "$ref": "#/components/schemas/File"

    # Champs utilisés
    Pays:
      description: Pays à la norme ISO3361-alpha2
      example: FR
      title: Pays
      type: string
    Distributeur:
      title: Distributeur
      type: object
      properties:
          nom:
            title: Nom du distributeur
            type: string
          nationalite:
            title: Nationalité du distributeur
            "$ref": "#/components/schemas/Pays"
    Norme:
      enum:
        - CE
        - International
        - CNR
        - ANSM
        - Inconnue
      title: Norme / Marquage
      type: string
    NatureProduit:
      enum:
        - Réactif
        - Autre dispositif
      title: Nature du produit
      type: string
    TechnologieTest:
      enum:
        - RT-PCR
        - Test rapide
        - Elisa
        - Autotest
      title: Technologie de test
      type: string
    TypeReactif:
      enum:
        - Amplification
        - Extraction
      title: Type de réactif
      type: string
    TypeCible:
      enum:
        - Anticorps
        - ARN Viral
      title: Type de cible
      type: string
    NombreCibles:
      enum:
        - 1
        - 2
        - "> 2"
      title: Nombre de cibles
      type: integer
    OuvertureTest:
      title: Test ouvert / fermé
      enum:
        - Ouvert
        - Fermé
        - NC
      type: string
    TypePrelevement:
      title: Type de prélèvement nécessaire au test
      enum:
        - Sérum
        - Plasma
        - Sang
        - Capillaire
        - Naso-pharyngé
        - Salive
        - Selles
        - Larmes
        - Autres
      type: string
    ModaliteAcheminementPrelevement:
      title: Modalité d'acheminement des prélèvements
      enum:
        - Emballage simple
        - Triple emballage
        - Chaîne du froid
        - Autres
      type: string
    FacteurDeVariation:
      title: Facteur faisant varier VPP/VPN/Se/Sp
      type: string
      enum:
        - Immunodépression
        - Grossesse
        - Âge
        - Immunité croisée
        - Autre
    DisponibiliteNationale:
      title: Capacité de livraison par mois
      type: array
      items:
        "$ref": "#/components/schemas/DisponibiliteNationaleDate"
    DisponibiliteNationaleDate:
      type: object
      properties:
        count:
          title: Capacité de livraison au niveau national
          type: integer
        mois:
          example: "Juin"
          title: Mois
          type: string
    UsageTest:
      title: Usage du test
      type: string
      enum:
        - Diagnostic pour prise en charge individuelle
        - Diagnostic pour cohorting
        - Diagnostic pour levée d'isolement personnel
        - Etude populationnelle pour guider les stratégies
        - Autre
    StrategieCanauxDistribution:
      title: Stratégie de canaux de distribution des tests
      type: string
      enum:
        - Hôpital
        - Médecine de ville
        - Laboratoires de ville
        - Pharmacies
        - Autre
    Statut:
      type: string
      enum:
        - Non validé
        - En cours d’évaluation
        - Validé
        - Inconnu
    StatutRemboursement:
      type: string
      enum:
        - Remboursé
        - Non remboursé
    File:
      type: string
      format: binary
