openapi: 3.0.0
info:
  title: Schema de définition des tests COVID-19
  description: Detail du schéma de données test COVID-19
  contact:
    name: Fabrique des Ministères sociaux
    url: https://github.com/SocialGouv/covid19-tests-schemas
    email: contact@fabrique.social.gouv.fr
paths:
  "/test":
    post:
      description: Création d'un nouveau test au COVID-19
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostTestResponse"
          description: Orientation
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostTestRequest"
        required: true

components:
  schemas:
    type: object
    PostTestRequest:
      description: Corps de la requête POST pour enregistrer le test
      required:
        - orientation
      properties:
        test:
          anyOf:
            - $ref: "#/components/schemas/Test"

    PostTestResponse:
      type: object
      description: Réponse de l'envoi du test
      example:
        data:
          success: true

    # Schema d'un test
    Test:
      type: object
      required:
        - nom
        - producteur
      properties:
        nom:
          title: Nom du test
          type: string
        producteur:
          title: Nom du fabricant
          type: string
          example:
            - PHILIPS
            - THOMSON
            - AKAI
        emailOperateur:
          title: Email nominatif de l’opérateur (fabricant, distributeur, mandataire, importateur) 
          type: string
          format: email
        paysProduction:
          "$ref": "#/components/schemas/PaysProduction"
        statut:
          title: Statut du test
          "$ref": "#/components/schemas/TestStatus"
        brouillon:
          title: Brouillon
          type: boolean
          default: true
        estConsidereComplet:
          title: Le dossier est complet
          type: boolean
          default: false
        validation_CE:
          title: Marquage CE
          type: boolean
          default: false
        validation_International:
          title: Validation International
          type: boolean
          default: false
        validation_CNR:
          title: Évaluation CNR
          "$ref": "#/components/schemas/ValidationStatusCNR"
        validation_ANSM:
          title: Vérifié ANSM
          type: boolean
          default: false
        conformite_HAS:
          title: Conformité HAS
          type: boolean
          default: false
        distributeur:
          "$ref": "#/components/schemas/Distributeur"
        natureProduit:
          "$ref": "#/components/schemas/NatureProduit"
        technologie:
          "$ref": "#/components/schemas/TechnologieTest"
        typeReactif:
          "$ref": "#/components/schemas/TypeReactif"
        typeCible:
          "$ref": "#/components/schemas/TypeCible"
        typeTest:
          "$ref": "#/components/schemas/TypeTest"
        nombreCibles:
          "$ref": "#/components/schemas/NombreCibles"
        machinesNecessaires:
          title: Automates compatibles
          type: string
        ouvertureTest:
          "$ref": "#/components/schemas/OuvertureTest"
        courbeCinetiquePositive:
          # type de donnée ?
          title: Courbe type de cinétique de positivité du test
          type: string
        courbeCinetiquePositiveDocs:
          title: "Documents relatifs à la courbe type de cinétique de positivité du test"
          type: array
          items:
            "$ref": "#/components/schemas/File"
        typePrelevement:
          title: Type de prélèvement nécessaire au test
          uniqueItems: true
          type: array
          items:
            "$ref": "#/components/schemas/TypePrelevement"
        proteines:
          title: Types de protéines détectées par le test
          uniqueItems: true
          type: array
          items:
            "$ref": "#/components/schemas/TypeProteine"
        modalitesAcheminementPrelevements:
          title: Modalités d'acheminement des prélèvements
          uniqueItems: true
          type: array
          items:
            "$ref": "#/components/schemas/ModaliteAcheminementPrelevement"
        nombreStructuresCapablesFrance:
          title: Nombre de structures en mesure de faire le test sur le territoire national
          type: integer
          minimum: 0
          maximum: 1000000
        conditionsConservation:
          "$ref": "#/components/schemas/ConditionsConservation"
        temperatureConservationMini:
          title: Température de conservation minimum
          type: number
        temperatureConservationMaxi:
          title: Température de conservation maximum
          type: number
        temperatureConservationMoy:
          title: Température de conservation moyenne
          type: number
        durabiliteGarantiePeremption:
          title: Durabilité garantie avant péremption (en mois)
          type: number
        consommables:
          title: Consommables indispensables et non compris dans le kit test
          type: array
          items:
            "$ref": "#/components/schemas/Consommables"
        delaiResultatMaximal:
          title: Délai maximal d'obtention du résultat du test (en minutes)
          type: integer
        valeurPredictivePositive:
          title: Valeur Prédictive positive
          type: string
        valeurPredictiveNegative:
          title: Valeur Prédictive négative
          type: string
        sensibilite:
          title: Sensibilité clinique déclarée par le fabricant (en %)
          type: string
        specificite:
          title: Spécificité clinique déclarée par le fabricant (en %)
          type: string
        facteursDeVariation:
          # choix multiple ?
          title: Facteurs faisant varier VPP/VPN/Se/Sp
          uniqueItems: true
          type: array
          items:
            "$ref": "#/components/schemas/FacteurDeVariation"
        limiteDetection:
          title: Limite de détection
          type: string
        fourchettePrixBasse:
          title: Fourchette de prix basse du test (en euros par test)
          type: integer
        fourchettePrixHaute:
          title: Fourchette de prix haute du test (en euros par test)
          type: integer
        disponibiliteNationale:
          "$ref": "#/components/schemas/DisponibiliteNationale"
        capaciteProductionHebdomadaire:
          title: Capacité de production par semaine
          type: integer
        usagesTest:
          title: Usages du test
          uniqueItems: true
          type: array
          items:
            "$ref": "#/components/schemas/UsageTest"
        strategiesCanauxDistribution:
          title: Stratégies de canaux de distribution des tests
          uniqueItems: true
          type: array
          items:
            "$ref": "#/components/schemas/StrategieCanauxDistribution"
        statutRemboursement:
          title: Statut du remboursement
          "$ref": "#/components/schemas/StatutRemboursement"
        signalementsReactovigilance:
          title: Signalements de réactovigilance
          type: string
        virologieTests:
          title: Pour les tests de virologie
          "$ref": "#/components/schemas/VirologieTests"
        performancesSerologieIgM:
          title: IgM
          "$ref": "#/components/schemas/PerformancesSerologieTestJ7"
        performancesSerologieIgG:
          title: IgG
          "$ref": "#/components/schemas/PerformancesSerologieTestJ14"
        performancesSerologieIgTotal:
          title: IgTotales
          "$ref": "#/components/schemas/PerformancesSerologieTestJ14"
        pointsContact:
          title: Points de contact
          type: string
        commentaires:
          title: Commentaires non visibles publiquement
          type: string
        commentairesPublics:
          title: Commentaires publics
          type: string
        documents:
          title: "Documents"
          type: array
          items:
            "$ref": "#/components/schemas/File"
        ficheProduit:
          title: "Fiche produit"
          type: array
          items:
            "$ref": "#/components/schemas/File"
        ficheSynthese:
          title: "Fiche de synthèse (au format PDF)"
          type: array
          items:
            "$ref": "#/components/schemas/File"
        sensibiliteAnalytique:
          title: Sensibilité analytique
          type: string
        sensibiliteDiagnostique:
          title: Sensibilité diagnostique (en %)
          type: string
        nbEchantillonsSensibilite:
          title: Nombre total d’échantillons positifs en RT-PCR testés pour la sensibilité
          type: integer
        specificiteDiagnostique:
          title: Spécificité diagnostique
          type: string
        nbEchantillonsSpecificite:
          title: Nombre total d’échantillons négatifs en RT-PCR testés pour la spécificité
          type: integer
        evaluation1:
          title: "Evaluation"
          "$ref": "#/components/schemas/Evaluation"
        docsEvaluation:
          title: "Documents d’évaluations"
          type: array
          items:
            "$ref": "#/components/schemas/File"
    Evaluation:
      type: object
      properties:
        nom:
          title: Evalué par
          type: string
        date:
          title: Date d'évaluation
          type: string
          format: date
        sensibilite:
          title: Sensibilité analytique (en % seuil de détection)
          type: string
        sensibiliteDiagnostique:
          title: Sensibilité diagnostique / clinique (en %)
          type: string
        nbEchantillonsSensibilite:
          title: Nombre total d’échantillons positifs en RT-PCR testés pour la sensibilité
          type: integer
        specificite:
          title: "Spécificité diagnostique / clinique"
          type: string
        nbEchantillonsSpecificite:
          title: Nombre total d’échantillons négatifs testés pour la spécificité
          type: integer
    PaysProduction:
      title: Pays de production
      type: object
      properties:
        pays1:
          title: Pays 1
          items:
            "$ref": "#/components/schemas/Pays"
        pays2:
          title: Pays 2
          items:
            "$ref": "#/components/schemas/Pays"
        pays3:
          title: Pays 3
          items:
            "$ref": "#/components/schemas/Pays"
    Pays:
      description: Pays à la norme ISO3361-alpha2
      example: FR
      title: Pays
      type: string
    VirologieTests:
      type: object
      properties:
        sensibiliteCNR:
          title: Sensibilité clinique évaluée par le CNR
          type: string
        specificiteCNR:
          title: Spécificité clinique évaluée par le CNR
          type: string
    PerformancesSerologieTestJ7:
      title: PerformancesSerologieTest
      type: object
      properties:
        sensibilite:
          title: Sensibilité cumulée à partir de J7 (%)
          type: integer
        specificite:
          title: Spécificité (%)
          type: integer
        ecartDeConfiance:
          title: Intervalle de confiance pour le calcul de la spécificité (%-%)
          type: string
        nombreEchantillons:
          title: Nombre d’échantillons pour le calcul de la spécificité
          type: integer
    PerformancesSerologieTestJ14:
      title: PerformancesSerologieTest
      type: object
      properties:
        sensibilite:
          title: Sensibilité cumulée à partir de J14 (%)
          type: integer
        specificite:
          title: Spécificité (%)
          type: integer
        ecartDeConfiance:
          title: Intervalle de confiance pour le calcul de la spécificité (%-%)
          type: string
        nombreEchantillons:
          title: Nombre d’échantillons pour le calcul de la spécificité
          type: integer
    Distributeur:
      title: Distributeur
      type: object
      properties:
        nom:
          title: Nom du distributeur
          type: string
        nationalite:
          title: Nationalité du distributeur
          "$ref": "#/components/schemas/Pays"
    NatureProduit:
      enum:
        - Réactif
        - Autre dispositif
      title: Nature du produit
      type: string
    TechnologieTest:
      enum:
        - RT PCR simple
        - RT PCR multiplex
        - RT LAMP
        - Sérologie automatisée (non TDR)
        - Sérologie rapide (dont TDR et TROD)
        - Antigénique automatisé
        - Antigénique non automatisé (dont TROD)
        - Autres
      title: Sous-type de test
      type: string
    TypeReactif:
      enum:
        - Amplification
        - Extraction
      title: Type de réactif
      type: string
    TypeTest:
      enum:
        - Amplification génique
        - Sérologique
        - Antigénique
        - Autre
      title: Type de test
      type: string
    TypeCible:
      enum:
        - Protéines N
        - Protéines S
        - IgM
        - IgG
        - IgA
        - Ig Totaux
        - Autre
      title: Type de cible
      type: string
    NombreCibles:
      enum:
        - 1
        - 2
        - "> 2"
      title: Nombre de cibles
      type: string
    OuvertureTest:
      title: Test ouvert / fermé
      enum:
        - Ouvert
        - Fermé
        - NC
      type: string
    ConditionsConservation:
      title: Conditions de conservation
      enum:
        - Température ambiante
        - Température contrôlée
      type: string
    TypePrelevement:
      title: Type de prélèvement (validé dans la notice du text)
      enum:
        - Sang total
        - Sérum / Plasma
        - Nasopharyngé
        - Crachat
        - Salive
        - "Écouvillon oropharyngé"
        - "Haleine / souffle"
        - Selles
        - Nasal
        - Expectoration
        - Autres
      type: string
    TypeProteine:
      title: Types de protéines détectées par le test
      enum:
        - N
        - S
      type: string
    ModaliteAcheminementPrelevement:
      title: Modalité d'acheminement des prélèvements
      enum:
        - Emballage simple
        - Triple emballage
        - Chaîne du froid
        - Autres
      type: string
    Consommables:
      title: Consommables
      enum:
        - Ecouvillon
        - Milieu de transport
        - Tube de collecte
        - Autre
      type: string
    FacteurDeVariation:
      title: Facteur faisant varier VPP/VPN/Se/Sp
      type: string
      enum:
        - Immunodépression
        - Grossesse
        - Âge
        - Immunité croisée
        - Autre
    DisponibiliteNationale:
      title: Capacité de livraison par mois
      type: array
      items:
        "$ref": "#/components/schemas/DisponibiliteNationaleDate"
    DisponibiliteNationaleDate:
      type: object
      properties:
        count:
          title: Capacité de livraison au niveau national
          type: integer
        mois:
          example: "Juin"
          title: Mois
          type: string
          enum:
            - Janvier
            - Février
            - Mars
            - Avril
            - Mai
            - Juin
            - Juillet
            - Août
            - Septembre
            - Octobre
            - Novembre
            - Décembre
    UsageTest:
      title: Usage du test
      type: string
      enum:
        - Diagnostic pour prise en charge individuelle
        - Diagnostic pour cohorting
        - Diagnostic pour levée d'isolement personnel
        - Etude populationnelle pour guider les stratégies
        - Autre
    StrategieCanauxDistribution:
      title: Stratégie de canaux de distribution des tests
      type: string
      enum:
        - Hôpital
        - Médecine de ville
        - Laboratoires de ville
        - Pharmacies
        - Infirmier(e)s
        - Autre
    TestStatus:
      type: string
      enum:
        - Public
        - Non public
    ValidationStatusCNR:
      type: string
      enum:
        - Avis favorable
        - En cours d’évaluation
        - En cours d’expédition
        - Non initié
        - Avis défavorable
        - Inconnu
    StatutRemboursement:
      type: string
      enum:
        - Remboursable
        - Non remboursable
    File:
      type: string
      format: binary
